version: "3"
services: 
  master:
    container_name: master
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes: 
      - ./jenkins_home:/var/jenkins_home
    # links 를 통해서 서비스끼리 연동할 수 있습니다. 
    links:
      - slave01
      - slave02
  # jenkins - slave 를 정의합니다. 
  # 환경변수를 아래와 같이 JENKINS_SLAVE_SSH_PUBKEY 로 접근 할 수 있습니다.
  slave01:
    container_name: slave01
    image: jenkins/ssh-slave
    environment: 
    - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}

  slave02:
    container_name: slave02
    image: jenkins/ssh-slave
    environment: 
      - JENKINS_SLAVE_SSH_PUBKEY=${JENKINS_SLAVE_SSH_PUBKEY}

